package:
  name: pyside6-datatable-widget
  version: 1.0.0

source:
  url: https://pypi.io/packages/source/p/pyside6-datatable-widget/pyside6-datatable-widget-1.0.0.tar.gz
  # or use local path: path: ../path/to/source

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyside6

about:
  home: https://github.com/ultra-bugs/pyside6-datatable-widget
  license: MIT
  summary: 'A powerful DataTable widget for PySide6 applications with functionality similar to jQuery DataTable.'
